[package]
name = "rusty-llms"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rusty-llms"
path = "src/main.rs"

[dependencies]
csv = "1.1"
dotenvy = "0.15.7"
llm-chain = "0.13.0"
llm-chain-openai = "0.13.0"
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
